### ISSUE TITLE
Please add following paper related to sentence embedding 

### ISSUE THREAD

**Issue by vinodkkurmi** [Hironsan/awesome-embedding-models#7]
@Hironsan 
Please add the following paper related to sentence embedding 
paper : Learning Semantic Sentence Embeddings using Pair-wise Discriminator
Project page and code:  https://badripatro.github.io/Question-Paraphrases/

Thanks

**Comment by Hironsan** [comment]
Thanks for sharing the information.
Could you please make a Pull Request?
